# Generated by Django 4.2.2 on 2023-06-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_direccion_customuser_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fechadenacimiento',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
    ]
