# Generated by Django 4.2.1 on 2023-06-02 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apilemone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fehamodificacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuarioalta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producto_usuarioalta', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='usuariomodificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producto_usuariomodificacion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaalta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
