# Generated by Django 4.2.1 on 2023-06-02 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apilemone', '0002_producto_fehamodificacion_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fehamodificacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuariomodificacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_usuariomodificacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
