# Generated by Django 4.2.2 on 2023-06-09 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apilemone', '0004_alter_producto_fehamodificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDeOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EstadoDeOrden',
                'verbose_name_plural': 'EstadosDeOrden',
                'db_table': 'estadodeorden',
            },
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MedioDePago',
                'verbose_name_plural': 'MediosDePago',
                'db_table': 'mediodepago',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nrodeorden', models.IntegerField()),
                ('nrodetransaccion', models.IntegerField()),
                ('importeneto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importeiva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importetotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(max_length=250)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fechaalta', models.DateField(default=django.utils.timezone.now)),
                ('estadodeorden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.estadodeorden')),
                ('mediodepago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.mediodepago')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='TipoDeEnvio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoDeEnvio',
                'verbose_name_plural': 'TiposDeEnvio',
                'db_table': 'tipodeenvio',
            },
        ),
        migrations.CreateModel(
            name='TipoDeOperacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoDeOperacion',
                'verbose_name_plural': 'TiposDeOperacion',
                'db_table': 'tipodeoperacion',
            },
        ),
        migrations.CreateModel(
            name='TipoDePersona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoDePersona',
                'verbose_name_plural': 'TiposDePersona',
                'db_table': 'tipodePersona',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('activoactualmente', models.BooleanField(default=True)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fechaalta', models.DateField(default=django.utils.timezone.now)),
                ('fehamodificacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tipodepersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodepersona')),
                ('usuarioalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_usuarioalta', to=settings.AUTH_USER_MODEL)),
                ('usuariomodificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_usuariomodificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.CharField(max_length=250)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fechaalta', models.DateField(default=django.utils.timezone.now)),
                ('fechabaja', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.producto')),
                ('usuarioalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordendetalle_usuarioalta', to=settings.AUTH_USER_MODEL)),
                ('usuariobaja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordendetalle_usuariobaja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden_Detalle',
                'verbose_name_plural': 'Ordenes_Detalle',
                'db_table': 'orden_detalle',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.persona'),
        ),
        migrations.AddField(
            model_name='orden',
            name='tipodeenvio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodeenvio'),
        ),
        migrations.AddField(
            model_name='orden',
            name='usuarioalta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_usuarioalta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fechaalta', models.DateField(default=django.utils.timezone.now)),
                ('fechabaja', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.persona')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.producto')),
                ('tipodeoperacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodeoperacion')),
                ('usuarioalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacion_usuarioalta', to=settings.AUTH_USER_MODEL)),
                ('usuariobaja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operacion_usuariobaja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'operacion',
            },
        ),
    ]
