# Generated by Django 4.2.1 on 2023-06-02 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('activoactualmente', models.BooleanField(default=True)),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('inventariominimo', models.IntegerField(default=20)),
                ('preciodecosto', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('preciodeventa', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('activoactualmente', models.BooleanField(default=True)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fechaalta', models.DateField(default=datetime.date(2023, 6, 2))),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
